### ISSUE TITLE
Screen Resolution Broken

### ISSUE THREAD

**Issue by Tall-Lobster** [Philrado/D-Dodger#1]
Dear Philrado,

I was running your game using the OpenTuring software, and I seem to be facing issues with screen resolution. Here is a picture to demonstrate the problem:
![Paste](https://user-images.githubusercontent.com/46766067/81014991-e1b9a780-8e2b-11ea-8f73-b4f9df6c33f0.png)

**Comment by Philrado** [comment]
Use the official Turing software instead and set your resolution to a far lower one as this was made with an old monitor as the default. 

Thank you for the catch!
